name: DAST Scan
on:
  push:
    branches: ["dast-scan"]

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        run: |
          cd Source
          docker-compose build

      - name: launch app
        run: docker-compose up --detach

      - name: OWASP ZAP
        uses: zaproxy/action-baseline@v0.4.0
        with:
           target: "http://localhost:8000"
           fail_action: false
           token: $
           issue_title: DAST Results
