name: Selenium Tests

on:
 push:
   branches: [ main, selenium_tests ]
 pull_request:
   branches: [main, selenium_tests ]

jobs:
 build:

   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   - name: Test selenium
     run: |
       python manage.py test
