name: unit-tests

on:
 push:
   branches: [ main, UnitTest-MatthewMcDaid ]
 pull_request:
   branches: [ main, UnitTest-MatthewMcDaid ]

jobs:
 build:

   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3
   - name: Install dependencies
     run: |
       cd Source
       python -m pip install --upgrade pip
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   - name: Run Selenium Tests
     run: |
       cd Source
       python manage.py test grassroots/tests/unitTests
